spring:
  profiles:
    active: dev

#notificador:
#  email:
#    host-servidor: draft-api.email.com.br
#    port-servidor: 25

#Adicionado após a implementação de NotificacaoEmail.java
#O auto-complete Funciona em arquivo propertie e yml
notificador:
  email:
    host-servidor: draft-api.email.com.br
    porta-servidor: 25
